name: dispatch receiver

on:
  repository_dispatch:
    types:
      - my_event
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dispatch trigger
      if: github.event.action == "my_event"
      run: |
        echo "repository_dispatch triggered"
